### PR TITLE
Wip/bewest/custom gatt profile

### PR DESCRIPTION
**Pull request by bewest**
Note taking... potentially add `Pair`, and `ConnectProfile`.
- http://www.bluez.org/bluez-5-api-introduction-and-porting-guide/
- https://git.kernel.org/cgit/bluetooth/bluez.git/tree/doc/gatt-api.txt
- https://git.kernel.org/cgit/bluetooth/bluez.git/tree/doc/device-api.txt

### CODE REVIEW

**Comment by bewest** [comment]
Howdy, I cleaned up some of the dbus changes I needed for https://github.com/bewest/Adafruit_Python_BluefruitLE/pull/1, https://github.com/bewest/openxshareble.

In particular, I found the UART class and examples very very helpful, thanks!
Has anyone thought about releasing it through pypi so projects can use a package manager to install the python lib?

**Comment by Fokko** [comment]
LGTM

**Comment by bewest** [comment]
Aside, there's some useful stuff in https://github.com/adafruit/Adafruit_Python_BluefruitLE/pull/7, I'm wondering if we can maybe sync up.

**Comment by bewest** [comment]
Aside, dbus-python is older, pydbus is the newer thing
Since dbus-python, pydbus has come around to replace `dbus-python` with `gdbus` based backend via `gi.repository` goodness.  I've highlighted a number of issues which have all been solved as of glib 2.45.

-----------

For posterity:

* https://bugzilla.gnome.org/show_bug.cgi?id=656330
* Naive attempt (missing an extra loop/threading thing ) https://github.com/bewest/Adafruit_Python_BluefruitLE/pull/3
* https://gist.github.com/bossjones/e054e224f5b8578dff0a#gistcomment-1710180
* https://github.com/LEW21/pydbus/issues/7

The updates in glib 2.45 are really only needed in the scenario where someone needs to export services on dbus by using ble.  In scenarios like this, the older `dbus-python` api has a problem where nested mainloops "coalesce" causing the event listeners to be duplicated.

I've spent several weeks evaluating pydbus, which really needs glib 2.45 to work, vs txdbus, versus the limitations of the older API.  The older API can be worked around in my scenario by promoting variety of "background threads" to full blown processes, all using the older API.  However, it's not really open to new features or patches (eg to [workaround properties](https://github.com/openaps/oacids/blob/master/oacids/helpers/dbus_props.py)), and pydbus is, pending glib 2.45 becoming more widely available.

I took a very brief stab at duplicating a lot of things to adapt the pydbus methods with minimal changes.  One big change I mad was eliminating the `dbus-pythhon`'s `DBusGMainLoop`, which naturally causes the first call to `Event.wait` to hang.  I've read in various places about either [iterating the mainloop](http://www.jejik.com/articles/2007/01/python-gstreamer_threading_and_the_main_loop/) and the [threading docs](https://wiki.gnome.org/Projects/PyGObject/Threading), as well as [techniques using generators](https://github.com/nathan-hoad/gbulb), but not quite sure how to proceed with "minimal changes" versus what redesigns using a pure pydbus API might be desired (for client, at least  until glib 2.45 is widespread)?

**Comment by scottleibrand** [comment]
Is this something that can be merged?  Or do we need to create a fork over at https://github.com/openaps/ for ongoing openxshareble support?

**Comment by PieterGit** [comment]
@adafruit can you tell us if this library is still updated, or we should fork it and maintain it. It's used as part of openaps. We need these patches and https://github.com/donatieng/Adafruit_Python_BluefruitLE/commit/af46b05cbcfd82110c8bbd08ed3d483de128fed1

**Comment by ladyada** [comment]
forking is best!

**Comment by dhalbert** [comment]
This library has been deprecated. Please update to use this new library:
https://github.com/adafruit/Adafruit_Blinka_bleio
PR's can be submitted to the new library.

**Pull request closed without merging**
