### PR TITLE
fix UUIDs on python3/macOS

### PR DESCRIPTION
**Pull request by joshbode**
Addresses #30 by fixing Python UUID conversion on macOS for Python 3.

### CODE REVIEW

**Comment by fallik** [comment]
Works for me, no more exceptions using macOS and my iPhone (running the Bluefruit App) as peripheral.

**Comment by joshbode** [comment]
Thanks for confirming @fallik :)

**Comment by emilyhorsman** [comment]
This fix works for me on:

- macOS 10.13.4
- Python 3.6.4
- pyobjc==4.2.2

Any chance of merging? I'd be happy to help resolve any blocking issues. :)

**Comment by emilyhorsman** [comment]
For anyone experiencing this issue and wanting to use this fix before it's merged you can run the following commands:

```
$ git fetch origin pull/31/head:p31
$ git checkout p31
$ sudo python3 setup.py install
```

**Comment by ladyada** [comment]
i'm ok with merging - but FYI we haven't tested it ourselves!

**Comment by emilyhorsman** [comment]
Any output/etc I can record to build confidence?

**Comment by joshbode** [comment]
We've used this branch successfully on macOS and Linux
cc: @jaredjxyz

**Comment by ladyada** [comment]
two volts make a yes! merging :)

**Comment by joshbode** [comment]
thanks @ladyada :)

**Comment by ladyada** [comment]
thank YALL for the help!! have a great weekend

**Pull request merged**
